#!/usr/bin/env python3
"""Package the add-on into an installable Kodi zip, with your keys baked in.

    python build.py            -> dist/plugin.video.trackmyshows-<version>.zip
    python build.py --serve    -> also serve dist/ on your LAN so Kodi can install from it

Keys are read from secrets/ (never committed):
    secrets/google_client.json   OAuth client downloaded from Google Cloud ("TVs and Limited Input devices")
    secrets/tmdb_api_key.txt     TMDb API key (v3 key or v4 read token)
"""
import argparse
import functools
import glob
import http.server
import json
import os
import re
import socket
import socketserver
import sys
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
ADDON_ID = 'plugin.video.trackmyshows'
SRC = os.path.join(ROOT, ADDON_ID)
SECRETS = os.path.join(ROOT, 'secrets')
DIST = os.path.join(ROOT, 'dist')
CREDENTIALS = 'resources/lib/tms/credentials.py'


def _find_client(obj):
    if isinstance(obj, dict):
        if obj.get('client_id') and obj.get('client_secret'):
            return obj['client_id'], obj['client_secret']
        for value in obj.values():
            found = _find_client(value)
            if found:
                return found
    return None


def load_secrets():
    client_id = client_secret = ''
    for path in sorted(glob.glob(os.path.join(SECRETS, '*.json'))):
        with open(path, encoding='utf-8') as f:
            found = _find_client(json.load(f))
        if found:
            client_id, client_secret = found
            print('Google client: %s (%s...)' % (os.path.basename(path), client_id[:12]))
            break
    else:
        print('WARNING: no Google client JSON in secrets/ - sync must be configured in add-on settings.')
    tmdb = ''
    tmdb_path = os.path.join(SECRETS, 'tmdb_api_key.txt')
    if os.path.exists(tmdb_path):
        with open(tmdb_path, encoding='utf-8') as f:
            tmdb = f.read().strip()
        print('TMDb key:      found')
    else:
        print('WARNING: secrets/tmdb_api_key.txt missing - identification and "Where was I?" need it.')
    return client_id, client_secret, tmdb


def bridge_cert():
    """Self-signed certificate for the add-on's phone remote server (made once, kept in secrets/)."""
    pem, key = os.path.join(SECRETS, 'bridge.pem'), os.path.join(SECRETS, 'bridge.key')
    if not (os.path.exists(pem) and os.path.exists(key)):
        import shutil
        import subprocess
        openssl = shutil.which('openssl')
        if not openssl:
            print('WARNING: openssl not found - the phone remote will be disabled in this build.')
            return None
        os.makedirs(SECRETS, exist_ok=True)
        subprocess.run([openssl, 'req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '3650',
                        '-keyout', key, '-out', pem, '-subj', '/CN=TrackMyShows TV remote'],
                       check=True, capture_output=True)
        print('Created phone-remote certificate in secrets/')
    return pem, key


def version():
    with open(os.path.join(SRC, 'addon.xml'), encoding='utf-8') as f:
        return re.search(r'<addon\b[^>]*\bversion="([^"]+)"', f.read()).group(1)


def build():
    client_id, client_secret, tmdb = load_secrets()
    credentials = ('# Generated by build.py\nGOOGLE_CLIENT_ID = %r\nGOOGLE_CLIENT_SECRET = %r\nTMDB_API_KEY = %r\n'
                   % (client_id, client_secret, tmdb))
    os.makedirs(DIST, exist_ok=True)
    out = os.path.join(DIST, '%s-%s.zip' % (ADDON_ID, version()))
    cert = bridge_cert()
    with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:
        if cert:
            z.write(cert[0], ADDON_ID + '/resources/bridge/bridge.pem')
            z.write(cert[1], ADDON_ID + '/resources/bridge/bridge.key')
        for folder, dirs, files in os.walk(SRC):
            dirs[:] = [d for d in dirs if d != '__pycache__']
            for name in files:
                if name.endswith(('.pyc', '.pyo')):
                    continue
                full = os.path.join(folder, name)
                rel = os.path.relpath(full, SRC).replace(os.sep, '/')
                arc = ADDON_ID + '/' + rel
                if rel == CREDENTIALS:
                    z.writestr(arc, credentials)
                else:
                    z.write(full, arc)
    print('Built %s' % out)
    return out


def lan_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(('10.255.255.255', 1))
        return s.getsockname()[0]
    except OSError:
        return '127.0.0.1'
    finally:
        s.close()


class RangeHandler(http.server.SimpleHTTPRequestHandler):
    """Static files with HTTP Range support: Kodi seeks inside zips when installing over HTTP."""

    extensions_map = {**http.server.SimpleHTTPRequestHandler.extensions_map, '.zip': 'application/zip'}

    def send_head(self):
        path = self.translate_path(self.path)
        match = re.match(r'bytes=(\d*)-(\d*)$', self.headers.get('Range', '').strip())
        if not match or not os.path.isfile(path):
            return super().send_head()
        size = os.path.getsize(path)
        start_s, end_s = match.groups()
        if start_s:
            start, end = int(start_s), min(int(end_s) if end_s else size - 1, size - 1)
        elif end_s:  # suffix range: the last N bytes
            start, end = max(size - int(end_s), 0), size - 1
        else:
            return super().send_head()
        if start >= size or start > end:
            self.send_response(416)
            self.send_header('Content-Range', 'bytes */%d' % size)
            self.end_headers()
            return None
        f = open(path, 'rb')
        f.seek(start)
        self.send_response(206)
        self.send_header('Content-Type', self.guess_type(path))
        self.send_header('Content-Range', 'bytes %d-%d/%d' % (start, end, size))
        self.send_header('Content-Length', str(end - start + 1))
        self.end_headers()
        self._remaining = end - start + 1
        return f

    def copyfile(self, source, outputfile):
        remaining = getattr(self, '_remaining', None)
        if remaining is None:
            return super().copyfile(source, outputfile)
        while remaining > 0:
            chunk = source.read(min(65536, remaining))
            if not chunk:
                break
            outputfile.write(chunk)
            remaining -= len(chunk)
        self._remaining = None

    def end_headers(self):
        self.send_header('Accept-Ranges', 'bytes')
        super().end_headers()


def serve(port):
    handler = functools.partial(RangeHandler, directory=DIST)
    with socketserver.ThreadingTCPServer(('', port), handler) as httpd:
        print('\nServing dist/ at  http://%s:%d/' % (lan_ip(), port), flush=True)
        print('In Kodi: Settings > File manager > Add source > enter that address,')
        print('then Add-ons > Install from zip file > pick that source. Ctrl+C to stop.')
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            pass


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--serve', action='store_true', help='serve dist/ over HTTP after building')
    ap.add_argument('--port', type=int, default=8089)
    args = ap.parse_args()
    build()
    if args.serve:
        serve(args.port)


if __name__ == '__main__':
    sys.exit(main())
